README.md

-----
[View rendered README.md](https://github.com/publiccodenet/jekyll-theme/blob/contextual-explainer-1/README.md)

Add contextual explainer

---

README.md
governance.md

Do you have any information about the process whereby governance decisions are taken?
-----
[View rendered governance.md](https://github.com/publiccodenet/jekyll-theme/blob/Governance/governance.md)

Create governance explanation, list of roles and list of stakeholder names

---

README.md

-----
[View rendered README.md](https://github.com/publiccodenet/jekyll-theme/blob/clarify-metadata-sentence/README.md)

Clarify English on metadata sentence in README.md

---

README.md

-----
[View rendered README.md](https://github.com/publiccodenet/jekyll-theme/blob/Improve-english-o/README.md)

Improve English under Navigation

---

CONTRIBUTING.md

Bigger changes will need to be reviewed according to governance.
-----
[View rendered CONTRIBUTING.md](https://github.com/publiccodenet/jekyll-theme/blob/contributing-governance/CONTRIBUTING.md)

added clause about and link to governance

---

README.md

Hi Boris, 
In order to make your codebase as collaborative as possible, I'd suggest simplifying some of the English. I also found a typo.
Claus 
-----
[View rendered README.md](https://github.com/publiccodenet/jekyll-theme/blob/Fix-performance-hint/README.md)

Fix English on 'performance hint'

---

_includes/footer.liquid
_includes/head.liquid

* Removed javascript
* Added link to code, issues and pull requests

Remove GitHub buttons

---

_includes/theme-footer.liquid

Addresses https://github.com/publiccodenet/about/issues/825

theme-footer: remove twitter

---

_includes/theme-nav.liquid

Retype 'Foundation for Public Code' in theme-nav.liquid

---

_includes/theme-nav.liquid
assets/style.css

Newly expanded header nav is now fully responsive!

Publiccode.net - Update nav header

---

_includes/theme-footer.liquid

Addresses publiccodenet/about#813

Update link to signup form

---

_includes/footer.liquid

Remove bullet point list to GitHub from site footer

---

_includes/footer.liquid

Add holder for translations snippet

---

_includes/page-information.liquid

Add optional section for feed

---

Gemfile

Was required on a newly upgraded machine.

Add explcit webrick dependency

---

README.md
_config.yml

null
-----
[View rendered README.md](https://github.com/publiccodenet/jekyll-theme/blob/no-travis/README.md)

We have switched from travis to GitHub workflows

---

README.md

null
-----
[View rendered README.md](https://github.com/publiccodenet/jekyll-theme/blob/fix-about-link/README.md)

fix about link

---

README.md

null
-----
[View rendered README.md](https://github.com/publiccodenet/jekyll-theme/blob/fixes_about_link/README.md)

fixes about link

---

.gitignore

Bundle suggests to install as
```
bundle config set --local path vendor/bundle
```
add to .gitignore

ignore bundle local path

---

_includes/prev_next.liquid

Add previous and next relations to links
