_includes/footer.liquid, _includes/github-search.svg, assets/style.css
This search bar:
* Uses GitHub's repository search page to search for
code, issues and pull requests
* Does not display on print media
So how this works:
1. You enter what you want to search for
2. GitHub opens on it's search page for that repository
So for example, on the about.publiccode.net you search for `contact`, it takes you to <https://github.com/publiccodenet/about/search?q=contact>
Closes #39 made by @felixfaassen and me.
=> Add repository search to repository information

_includes/metadata.liquid, _includes/page-information.liquid
While auditing the Public Code websites I think I found a little issue in the metadata sidebar: On several pages an empty table is displayed.
Inspect the sidebar on these pages for example:
- https://about.publiccode.net/
- https://about.publiccode.net/activities/
- https://about.publiccode.net/activities/documentation/
For the title:
I have been assuming that the intended behaviour is to keep the ability to display a title even if the table below is empty (as it seems to be currently the case on https://about.publiccode.net/)
For the table itself:
I have been assuming that: this table should only be displayed if there is at least one field in it.
=> Remove empty table and adding extra conditions for its display

_includes/footer.liquid
Using the GitHub information available in Jekyll.
This means that it will always show the release information available at build time.
This means it is wise to make a release on your release branch
before merging to the branch Jekyll builds from.
Features:
* Tag and prerelease status in header
* Publishing date and GitHub release page link
* Release name in own paragraph
* Assets as download links
=> Add release information

_includes/theme-footer.liquid, assets/style.css
**Housekeeping:** 
Transferred the footer update issue from _publiccode.net_ to _jekyll-theme_, as the affected files are both in the latter repo.
**Updated files:** 
1. Added structure and content to theme-footer.liquid, which contains the bottom-most footer (in the grey)
2. Added footer-related CSS code to main style.css. (Note: Written in plain CSS to stay consistent with existing code, not SCSS as with other updates).
**Considerations/Caveats:**
1. This includes some language changes (exactly as shown in the design comps in the issue), including most notably changing "About" to "How-to"
2. Though these files are contained in _jekyll-theme_, the update should be site-wide, as (if I am not mistaken) all subdomains make use of the same footer theme-footer.liquid file
**Travis status:** …
=> Publiccode.net new theme footer design

_includes/theme-footer-logo.liquid, _layouts/theme.liquid
**In order to:** 
1. Remove the nav links from the footer (https://github.com/publiccodenet/jekyll-theme/issues/41)
2. Retain the logo and links in the page header
3. Retain the logo in the footer
**And given that:** The nav bar is currently a single file mirrored in the header and footer...
**I have:**
1. Created a new footer file (_theme-footer-logo.liquid_) containing just the logo: 
2. Updated _theme.liquid_ to refer to this new file in the footer, while continuing to add the original theme-nav.liquid in the page header
=> Splitting nav mirroring into header (w/ nav) and footer (just logo)

_includes/theme-footer.liquid
As discussed here: https://github.com/publiccodenet/jekyll-theme/issues/55
=> Add site-wide license (+ caveat verbiage) to bottom of footer

_includes/theme-footer.liquid
Resolving Boris' concern about 'Get meta' wording being perceived as unserious.
https://github.com/publiccodenet/jekyll-theme/issues/62
=> Improving 'About us' link title in footer

_includes/page-information.liquid
The removed statement was actually necessary.
It enables overwriting the site wide setting per page.
The table of content stopped functioning entirely when not set per page and sitewide.
Fixes #69
=> Fix missing table of contents

_includes/footer.liquid
Adding a variable that can be set in the _config.yml to show a html snippet with badges in the footer. The snippet is defined in a separate file and included.
Part of the solution for publiccodenet/standard#519
=> Add possibility to show badges in footer

CONTRIBUTING.md
Fixes #30
-----
[View rendered CONTRIBUTING.md](https://github.com/publiccodenet/jekyll-theme/blob/ja-mailing-list/CONTRIBUTING.md)
=> Add link to new mailing list

_includes/prev_next.liquid, _layouts/single-page.liquid, assets/style.css
Pages must be part of a list which have an 'order' attribute.
A link will be created to the page with an 'order' attribute of 1
less than the current page 'order', if such a page is in the list.
Also, a link will be created to the page which has an order of 1
greater, if it exists.
=> Add prev-next navigation if show_prev_next: true

_includes/theme-nav.liquid
As suggested by @Ainali in #75
Also removed redundant 'Title' tags, as suggested by WAVE: https://wave.webaim.org/report#/publiccode.net
=> Hide the mark from accessibility tools

_includes/prev_next.liquid
When deploying publiccodenet.github.io/community-translations-standard
we noticed that the base url was not being included.
This is not an issue for the Standard site as the baseurl is "/".
Co-authored-by: Jan Ainali <ainali.jan@gmail.com>
=> Add site.baseurl to next/prev links

_includes/header.liquid
See: https://mademistakes.com/mastering-jekyll/site-url-baseurl/
for a good diagram of site.url, site.baseurl and page.url
Co-authored-by: Jan Ainali <ainali.jan@gmail.com>
=> Include site.baseurl in header

_includes/head.liquid
This should enable us to track visits across subdomains in different plausible sites.
It works by sending the actual URL to Plausible instead of always 'publiccode.net'.
=> Plausible: use subdomains

_includes/footer.liquid
Fixes #90
There might be a more direct and future-proof way to solve this, possibly through `{{ site.github.releases_html_url }}`, but it is hard to test since this repository doesn't have any releases. And my solution works until GitHub decides to put the releases under another URL than just `/releases`.
=> Add link to all releases

_includes/page-information.liquid
`feed` could not be used since it is reserved for jekyll-feed and `site.` was needed to make it match.
=> Change parameter name and referral

_includes/page-information.liquid
This was an unfortunate mistake by me, but the feed is located at /feed.xml not just /feed
=> Correcting link target of feed

_includes/metadata.liquid
This allows us to in the blog to get more metadata about authors in the feed. (We need to change that csv to yml though).
This change can be tested locally by adding the frontmatter 
```
---
author: Jan Ainali
---
```
to one file (for example [governance.md](https://github.com/publiccodenet/jekyll-theme/blob/master/governance.md)), then adding a folder named `_data` and add a file `authors.yml` in it. That file can have content like this:
```
Jan Ainali:
name: Ainali
twitter: Jan_Ainali
```
When serving the site, and viewing the file the addition was made to, the Author should be shown as "Ainali", not "Jan Ainali".
One can also check another page to make sure Author does not show up.
=> Add author info from data file

README.md
Thought this might be handy to have here?
-----
[View rendered README.md](https://github.com/publiccodenet/jekyll-theme/blob/adds_redirect_instructions_to_README/README.md)
=> adds redirect guide to README

_includes/theme-nav.liquid
In order to make the line break follow the instructions in https://brand.publiccode.net/name/ non-breaking spaces have been added between Foundation and for, and between Public and Code.
=> Add non breaking spaces to name
